### ISSUE TITLE
[OpenGL]Uniform Issue in OpenGL

### ISSUE THREAD

**Issue by doyoung413** [CubeBerry/CubeEngine#20]
## What is an issue?
Object's sprite appears correctly in Vulkan but not in OpenGL.
## Expected Causes
The issue may be with the uniform vectors used to send sprite information to the shader in OpenGL rendering.
## Expected Solutions
Need to modify the uniform-related parts in OpenGL

**Comment by CubeBerry** [comment]
```cpp
switch (attribute.component_type)
{
case GL_FLOAT:
	//For Float
	glCheck(glVertexArrayAttribFormat(vaoHandle, attribute.vertex_layout_location, attribute.component_dimension, attribute.component_type, attribute.normalized, attribute.relative_offset));
	break;
case GL_INT:
	//For Int
	glCheck(glVertexArrayAttribIFormat(vaoHandle, attribute.vertex_layout_location, attribute.component_dimension, attribute.component_type, attribute.relative_offset));
	break;
}
```
When setting Vertex Attributes of VAO, glVertexArrayAttribFormat is for FLOAT, and glVertexArrayAttribIFormat is for INT. The reason was that only glVertexArrayAttribFormat function was used for both FLOAT and INT.
