### ISSUE TITLE
[Engine]Program Freezes When Minimized

### ISSUE THREAD

**Issue by CubeBerry** [CubeBerry/CubeEngine#28]
## What is an issue?
On both OpenGL, and Vulkan, the program freezes when minimized. It also make entire Windows freezing on some PCs.

## Expected Causes
Suspected Multi-Thread but it was not the reason. Maybe SDL2 event causes this problem.

## Expected Solutions
No expected solutions yet.

**Comment by doyoung413** [comment]
<img width="566" alt="pic" src="https://github.com/user-attachments/assets/a767c03a-b3d7-4886-8288-4a1802953e91">
- When the window is minimized, the program freezes when using the SDL_SetWindow function.
- To fix this, modified the function that changes the window title so it doesn't execute when the SDL2 window is minimized.
